# Enable or disable commands here
# true = enabled, false = disabled
NPRestart: false
NPStop: false
Sit: false
UnSit: false
Calc: false

Search: false
SearchUrls:
  - 'https://www.google.com/#q=[SEARCH]'
  - 'https://duckduckgo.com/?q=[SEARCH]'
SearchSpace:
  - '+'
  - '+'
SearchMsg:
  - 'Search google: &6[LINK]'
  - 'Search duck duck go: &6[LINK]'